INSERT INTO veicoli (nome, tipologia, alimentazione, disponibilita, id_utente)
VALUES ("Fiat 500", "Automobile", "Elettrica", true, 1),
 ("Fiat 500", "Automobile", "Elettrica", true, 1),
 ("Fiat 500", "Automobile", "Elettrica", true, 1),
 ("Fiat 500", "Automobile", "Elettrica", true, 1),
 ("Fiat 500", "Automobile", "Elettrica", true, 1),
 ("Audi Q4", "Automobile", "Elettrica", true, 1),
 ("Audi Q4", "Automobile", "Elettrica", true, 1),
 ("Audi Q4", "Automobile", "Elettrica", true, 1),
 ("Audi Q4", "Automobile", "Elettrica", true, 1),
 ("Audi Q4", "Automobile", "Elettrica", true, 1),
 ("Mini Cooper S", "Automobile", "Elettrica", true, 1),
 ("Mini Cooper S", "Automobile", "Elettrica", true, 1),
 ("Mini Cooper S", "Automobile", "Elettrica", true, 1),
 ("Mini Cooper S", "Automobile", "Elettrica", true, 1),
 ("Mini Cooper S", "Automobile", "Elettrica", true, 1),
 ("Smart Fortwo", "Automobile", "Elettrica", true, 1),
 ("Smart Fortwo", "Automobile", "Elettrica", true, 1),
 ("Smart Fortwo", "Automobile", "Elettrica", true, 1),
 ("Smart Fortwo", "Automobile", "Elettrica", true, 1),
 ("Smart Fortwo", "Automobile", "Elettrica", true, 1),
 ("Smart Fortwo", "Automobile", "Elettrica", true, 1),
 ("Tesla Model 3", "Automobile", "Elettrica", true, 1),
 ("Tesla Model 3", "Automobile", "Elettrica", true, 1),
 ("Tesla Model 3", "Automobile", "Elettrica", true, 1),
 ("Volkswagen e-up!", "Automobile", "Elettrica", true, 1),
 ("Volkswagen e-up!", "Automobile", "Elettrica", true, 1),
 ("Volkswagen e-up!", "Automobile", "Elettrica", true, 1),
 ("Volkswagen e-up!", "Automobile", "Elettrica", true, 1),
 ("Volkswagen e-up!", "Automobile", "Elettrica", true, 1),
 ("Fiat 500X", "Automobile", "Diesel", true, 1),
 ("Fiat 500X", "Automobile", "Diesel", true, 1),
 ("Fiat 500X", "Automobile", "Diesel", true, 1),
 ("Fiat 500X", "Automobile", "Diesel", true, 1),
 ("Fiat 500X", "Automobile", "Diesel", true, 1),
 ("Alfa Romeo Giulia", "Automobile", "Diesel", true, 1),
 ("Alfa Romeo Giulia", "Automobile", "Diesel", true, 1),
 ("Alfa Romeo Giulia", "Automobile", "Diesel", true, 1),
 ("Alfa Romeo Giulia", "Automobile", "Diesel", true, 1),
 ("Alfa Romeo Giulia", "Automobile", "Diesel", true, 1),
 ("Fiat 500 Cabrio", "Automobile", "Benzina", true, 1),
 ("Fiat 500 Cabrio", "Automobile", "Benzina", true, 1),
 ("Fiat 500 Cabrio", "Automobile", "Benzina", true, 1),
 ("Fiat 500 Cabrio", "Automobile", "Benzina", true, 1),
 ("Fiat 500 Cabrio", "Automobile", "Benzina", true, 1),
 ("Fiat 500 Cabrio", "Automobile", "Benzina", true, 1),
 ("Fiat Tipo", "Automobile", "Benzina", true, 1),
 ("Fiat Tipo", "Automobile", "Benzina", true, 1),
 ("Fiat Tipo", "Automobile", "Benzina", true, 1),
 ("Fiat Tipo", "Automobile", "Benzina", true, 1),
 ("Fiat Tipo", "Automobile", "Benzina", true, 1),
 ("Mini Cooper", "Automobile", "Benzina", true, 1),
 ("Mini Cooper", "Automobile", "Benzina", true, 1),
 ("Mini Cooper", "Automobile", "Benzina", true, 1),
 ("Mini Cooper", "Automobile", "Benzina", true, 1),
 ("Mini Cooper", "Automobile", "Benzina", true, 1),
 ("Vespa", "Motocicletta", "Elettrica", true, 1),
 ("Vespa", "Motocicletta", "Elettrica", true, 1),
 ("Vespa", "Motocicletta", "Elettrica", true, 1),
 ("Vespa", "Motocicletta", "Elettrica", true, 1),
 ("Vespa", "Motocicletta", "Elettrica", true, 1),
 ("Vespa", "Motocicletta", "Elettrica", true, 1),
 ("Vespa", "Motocicletta", "Elettrica", true, 1),
 ("Vespa", "Motocicletta", "Elettrica", true, 1),
 ("Vespa", "Motocicletta", "Elettrica", true, 1),
 ("Vespa", "Motocicletta", "Elettrica", true, 1),
 ("City Bike", "Bicicletta", "Elettrica", true, 1),
 ("City Bike", "Bicicletta", "Elettrica", true, 1),
 ("City Bike", "Bicicletta", "Elettrica", true, 1),
 ("City Bike", "Bicicletta", "Elettrica", true, 1),
 ("City Bike", "Bicicletta", "Elettrica", true, 1),
 ("City Bike", "Bicicletta", "Elettrica", true, 1),
 ("City Bike", "Bicicletta", "Elettrica", true, 1),
 ("City Bike", "Bicicletta", "Elettrica", true, 1),
 ("City Bike", "Bicicletta", "Elettrica", true, 1),
 ("City Bike", "Bicicletta", "Elettrica", true, 1),
 ("City Bike", "Bicicletta", "Elettrica", true, 1),
 ("City Bike", "Bicicletta", "Elettrica", true, 1),
 ("Monopattino", "Monopattino", "Elettrica", true, 1),
 ("Monopattino", "Monopattino", "Elettrica", true, 1),
 ("Monopattino", "Monopattino", "Elettrica", true, 1),
 ("Monopattino", "Monopattino", "Elettrica", true, 1),
 ("Monopattino", "Monopattino", "Elettrica", true, 1),
 ("Monopattino", "Monopattino", "Elettrica", true, 1),
 ("Monopattino", "Monopattino", "Elettrica", true, 1),
 ("Monopattino", "Monopattino", "Elettrica", true, 1),
 ("Monopattino", "Monopattino", "Elettrica", true, 1);
 
INSERT INTO veicoli (nome, tipologia, disponibilita, id_utente)
VALUES ("Mountain Bike", "Bicicletta", true, 1),
("Mountain Bike", "Bicicletta", true, 1),
("Mountain Bike", "Bicicletta", true, 1),
("Mountain Bike", "Bicicletta", true, 1),
("Mountain Bike", "Bicicletta", true, 1),
("Mountain Bike", "Bicicletta", true, 1),
("Mountain Bike", "Bicicletta", true, 1),
("Graziella", "Bicicletta", true, 1),
("Graziella", "Bicicletta", true, 1),
("Graziella", "Bicicletta", true, 1),
("Graziella", "Bicicletta", true, 1),
("Graziella", "Bicicletta", true, 1),
("Graziella", "Bicicletta", true, 1),
("Graziella", "Bicicletta", true, 1),
("Graziella", "Bicicletta", true, 1),
("Graziella", "Bicicletta", true, 1),
("Graziella", "Bicicletta", true, 1),
("Graziella", "Bicicletta", true, 1),
("Graziella", "Bicicletta", true, 1),
("Graziella", "Bicicletta", true, 1);


