ALTER TABLE `veicoli` CHANGE `descrizione` `descrizione` VARCHAR(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL;

UPDATE `veicoli` SET `modello`= 'E-Moon' WHERE `modello`= 'City Bike';
UPDATE `veicoli` SET `modello`= 'Olanda ‘26' WHERE `modello`= 'Graziella';
UPDATE `veicoli` SET `alimentazione`= 'Pedalata Muscolare' WHERE `modello`= 'Olanda ‘26';

UPDATE `veicoli` SET `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole. Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `veicoli`.`id_veicolo` = 67;

UPDATE `veicoli` SET `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole. Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `veicoli`.`id_veicolo` = 68;

UPDATE `veicoli` SET `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole. Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `veicoli`.`id_veicolo` = 69;

UPDATE `veicoli` SET `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole. Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `veicoli`.`id_veicolo` = 70;

UPDATE `veicoli` SET `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole. Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `veicoli`.`id_veicolo` = 71;

UPDATE `veicoli` SET `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole. Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `veicoli`.`id_veicolo` = 72;

UPDATE `veicoli` SET `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole. Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `veicoli`.`id_veicolo` = 73;

UPDATE `veicoli` SET `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole. Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `veicoli`.`id_veicolo` = 74;

UPDATE `veicoli` SET `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole. Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `veicoli`.`id_veicolo` = 75;

UPDATE `veicoli` SET `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole. Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `veicoli`.`id_veicolo` = 76;

UPDATE `veicoli` SET `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole. Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `veicoli`.`id_veicolo` = 77;

UPDATE `veicoli` SET `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole. Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `veicoli`.`id_veicolo` = 78;

UPDATE `veicoli` SET `descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `veicoli`.`id_veicolo` = 95;

UPDATE `veicoli` SET `descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `veicoli`.`id_veicolo` = 96;

UPDATE `veicoli` SET `descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `veicoli`.`id_veicolo` = 97;
UPDATE `veicoli` SET `descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `veicoli`.`id_veicolo` = 98;
UPDATE `veicoli` SET `descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `veicoli`.`id_veicolo` = 99;
UPDATE `veicoli` SET `descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `veicoli`.`id_veicolo` = 100;
UPDATE `veicoli` SET `descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `veicoli`.`id_veicolo` = 101;
UPDATE `veicoli` SET `descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `veicoli`.`id_veicolo` = 102;
UPDATE `veicoli` SET `descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `veicoli`.`id_veicolo` = 103;
UPDATE `veicoli` SET `descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `veicoli`.`id_veicolo` = 104;
UPDATE `veicoli` SET `descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `veicoli`.`id_veicolo` = 105;
UPDATE `veicoli` SET `descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `veicoli`.`id_veicolo` = 106;
UPDATE `veicoli` SET `descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `veicoli`.`id_veicolo` = 107;

UPDATE `veicoli` SET `modello`= 'Olanda ‘26',`descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `id_veicolo` = 94;
UPDATE `veicoli` SET `modello`= 'Olanda ‘26', `descrizione` = 'La bicicletta Olanda ‘26, della Alpina bike, ha un telaio in alluminio e un design retrò con forme semplici ma funzionali. Questa bicicletta classica accoglie i gusti di tutti perché è una bellissima bicicletta da passeggio,  ideale per le passeggiate all’aria aperta e per visitare la città. I cerchi da 26’ risultano comodi e rendono la bicicletta maneggevole e confortevole.' WHERE `id_veicolo` = 93;
UPDATE `veicoli` SET `modello`= 'E-Moon ',`descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole.
Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di  un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `id_veicolo` = 92;
UPDATE `veicoli` SET `modello`= 'E-Moon ', `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole.
Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di  un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `id_veicolo` = 91;
UPDATE `veicoli` SET `modello`= 'E-Moon ',`descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole.
Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di  un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `id_veicolo` = 90;
UPDATE `veicoli` SET `modello`= 'E-Moon ', `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole.
Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di  un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `id_veicolo` = 89;
UPDATE `veicoli` SET `modello`= 'E-Moon ', `descrizione` = 'La bicicletta elettrica E-Moon, dei Flli. Schiano, ha un telaio in alluminio con attacco al manubrio regolabile che permette di tenere la posizione del corpo ed una guida confortevole.
Questa bicicletta elettrica è dotata di un motore anteriore ANANDA M129F da 250w che offre una lunga durata ed alte prestazioni e che può raggiungere una velocità massima di 25km/h e di  un cambio Shimano Tourney TY21 che permette di selezionare facilmente 7 velocità per ogni tipo di strada tu voglia percorrere.' WHERE `id_veicolo` = 88;

UPDATE `veicoli` SET `alimentazione` = 'Pedalata Muscolare' WHERE `veicoli`.`id_veicolo` = 94;
UPDATE `veicoli` SET `alimentazione` = 'Pedalata Muscolare' WHERE `veicoli`.`id_veicolo` = 95;

UPDATE `veicoli` SET `alimentazione` = 'Elettrica' WHERE `veicoli`.`id_veicolo` = 88;
UPDATE `veicoli` SET `alimentazione` = 'Elettrica' WHERE `veicoli`.`id_veicolo` = 89;
UPDATE `veicoli` SET `alimentazione` = 'Elettrica' WHERE `veicoli`.`id_veicolo` = 90;
UPDATE `veicoli` SET `alimentazione` = 'Elettrica' WHERE `veicoli`.`id_veicolo` = 91;
UPDATE `veicoli` SET `alimentazione` = 'Elettrica' WHERE `veicoli`.`id_veicolo` = 92;
UPDATE `veicoli` SET `alimentazione` = 'Elettrica' WHERE `veicoli`.`id_veicolo` = 93;