UPDATE `veicoli` SET `modello`= 'Fiat 500' WHERE `modello`= 'Mini Cooper S';
UPDATE `veicoli` SET `modello`= 'Fiat 500' WHERE `modello`= 'Smart Fortwo';
UPDATE `veicoli` SET `modello`= 'Fiat 500' WHERE `modello`= 'Volkswagen Scirocco';
UPDATE `veicoli` SET `alimentazione`= 'Elettrica' WHERE `id_veicolo`= 1;
UPDATE `veicoli` SET `modello`= 'Audi e-tron' WHERE `modello`= 'Tesla Model 3';
UPDATE `veicoli` SET `modello`= 'Audi e-tron' WHERE `modello`= 'Volkswagen e-up!';

UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 1;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 2;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 3;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 4;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 5;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 6;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 7;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 8;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 9;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 10;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 11;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 12;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 13;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 14;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 15;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 16;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 17;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 18;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 19;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 20;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 21;
UPDATE `veicoli` SET `descrizione` = 'Grazie alla sua tecnologia, Nuova 500 è più sicura che mai: il suo Fiat Co-Driver con Traffic Jam Assist ti aiuterà durante i tuoi viaggi. Da ora in poi la tua auto manterrà autonomamente la distanza dal veicolo che ti precede, accelererà, frenerà e rimarrà al centro della corsia di marcia, a qualsiasi velocità o condizione di traffico: sarà il tuo co-pilota di fiducia. Date le sue dimensioni compatte, la 500 elettrica è l’ideale per girare in città.' WHERE `veicoli`.`id_veicolo` = 22;

UPDATE `veicoli` SET `descrizione` = 'Il primo modello Audi completamente elettrico è pronto a conquistare la strada. Grazie a due motori elettrici capaci di erogare fino a 408 CV, la nuova e-tron garantisce il massimo delle performance in ogni condizione, senza scendere a compromessi.
La trazione integrale elettrica, abbinata a una batteria ad alta tensione che garantisce un’autonomia di oltre 400 chilometri nel ciclo WLTP, rende il nuovo SUV Audi perfetto per viaggiare ovunque vi portino i vostri desideri, senza rinunciare a comfort e a prestazioni da vera sportiva.' WHERE `veicoli`.`id_veicolo` = 23;
UPDATE `veicoli` SET `descrizione` = 'Il primo modello Audi completamente elettrico è pronto a conquistare la strada. Grazie a due motori elettrici capaci di erogare fino a 408 CV, la nuova e-tron garantisce il massimo delle performance in ogni condizione, senza scendere a compromessi.
La trazione integrale elettrica, abbinata a una batteria ad alta tensione che garantisce un’autonomia di oltre 400 chilometri nel ciclo WLTP, rende il nuovo SUV Audi perfetto per viaggiare ovunque vi portino i vostri desideri, senza rinunciare a comfort e a prestazioni da vera sportiva.' WHERE `veicoli`.`id_veicolo` = 24;
UPDATE `veicoli` SET `descrizione` = 'Il primo modello Audi completamente elettrico è pronto a conquistare la strada. Grazie a due motori elettrici capaci di erogare fino a 408 CV, la nuova e-tron garantisce il massimo delle performance in ogni condizione, senza scendere a compromessi.
La trazione integrale elettrica, abbinata a una batteria ad alta tensione che garantisce un’autonomia di oltre 400 chilometri nel ciclo WLTP, rende il nuovo SUV Audi perfetto per viaggiare ovunque vi portino i vostri desideri, senza rinunciare a comfort e a prestazioni da vera sportiva.' WHERE `veicoli`.`id_veicolo` = 25;
UPDATE `veicoli` SET `descrizione` = 'Il primo modello Audi completamente elettrico è pronto a conquistare la strada. Grazie a due motori elettrici capaci di erogare fino a 408 CV, la nuova e-tron garantisce il massimo delle performance in ogni condizione, senza scendere a compromessi.
La trazione integrale elettrica, abbinata a una batteria ad alta tensione che garantisce un’autonomia di oltre 400 chilometri nel ciclo WLTP, rende il nuovo SUV Audi perfetto per viaggiare ovunque vi portino i vostri desideri, senza rinunciare a comfort e a prestazioni da vera sportiva.' WHERE `veicoli`.`id_veicolo` = 26;
UPDATE `veicoli` SET `descrizione` = 'Il primo modello Audi completamente elettrico è pronto a conquistare la strada. Grazie a due motori elettrici capaci di erogare fino a 408 CV, la nuova e-tron garantisce il massimo delle performance in ogni condizione, senza scendere a compromessi.
La trazione integrale elettrica, abbinata a una batteria ad alta tensione che garantisce un’autonomia di oltre 400 chilometri nel ciclo WLTP, rende il nuovo SUV Audi perfetto per viaggiare ovunque vi portino i vostri desideri, senza rinunciare a comfort e a prestazioni da vera sportiva.' WHERE `veicoli`.`id_veicolo` = 27;
UPDATE `veicoli` SET `descrizione` = 'Il primo modello Audi completamente elettrico è pronto a conquistare la strada. Grazie a due motori elettrici capaci di erogare fino a 408 CV, la nuova e-tron garantisce il massimo delle performance in ogni condizione, senza scendere a compromessi.
La trazione integrale elettrica, abbinata a una batteria ad alta tensione che garantisce un’autonomia di oltre 400 chilometri nel ciclo WLTP, rende il nuovo SUV Audi perfetto per viaggiare ovunque vi portino i vostri desideri, senza rinunciare a comfort e a prestazioni da vera sportiva.' WHERE `veicoli`.`id_veicolo` = 28;
UPDATE `veicoli` SET `descrizione` = 'Il primo modello Audi completamente elettrico è pronto a conquistare la strada. Grazie a due motori elettrici capaci di erogare fino a 408 CV, la nuova e-tron garantisce il massimo delle performance in ogni condizione, senza scendere a compromessi.
La trazione integrale elettrica, abbinata a una batteria ad alta tensione che garantisce un’autonomia di oltre 400 chilometri nel ciclo WLTP, rende il nuovo SUV Audi perfetto per viaggiare ovunque vi portino i vostri desideri, senza rinunciare a comfort e a prestazioni da vera sportiva.' WHERE `veicoli`.`id_veicolo` = 29;
UPDATE `veicoli` SET `descrizione` = 'Il primo modello Audi completamente elettrico è pronto a conquistare la strada. Grazie a due motori elettrici capaci di erogare fino a 408 CV, la nuova e-tron garantisce il massimo delle performance in ogni condizione, senza scendere a compromessi.
La trazione integrale elettrica, abbinata a una batteria ad alta tensione che garantisce un’autonomia di oltre 400 chilometri nel ciclo WLTP, rende il nuovo SUV Audi perfetto per viaggiare ovunque vi portino i vostri desideri, senza rinunciare a comfort e a prestazioni da vera sportiva.' WHERE `veicoli`.`id_veicolo` = 30;