UPDATE `veicoli` SET `modello`= 'Ibsun L10' WHERE `modello`= 'Monopattino';


UPDATE `veicoli` SET `descrizione` = 'Il Monopattino elettrico Ibsun L10 ha un potente motore da 350W che può raggiungere fino ai 25km/h con un’autonomia di 58km e può trasportare un carico massimo di 150kg. È dotato di un sistema frenante meccanico ed elettrico Anti-Lock, che garantisce la sicurezza di frenata. Gli ammortizzatori anteriori e posteriori e gli ammortizzatori a molla anteriori garantiscono il massimo comfort e una guida fluida anche su superfici ruvide o dossi.' WHERE `veicoli`.`id_veicolo` = 79;
UPDATE `veicoli` SET `descrizione` = 'Il Monopattino elettrico Ibsun L10 ha un potente motore da 350W che può raggiungere fino ai 25km/h con un’autonomia di 58km e può trasportare un carico massimo di 150kg. È dotato di un sistema frenante meccanico ed elettrico Anti-Lock, che garantisce la sicurezza di frenata. Gli ammortizzatori anteriori e posteriori e gli ammortizzatori a molla anteriori garantiscono il massimo comfort e una guida fluida anche su superfici ruvide o dossi.' WHERE `veicoli`.`id_veicolo` = 80;
UPDATE `veicoli` SET `descrizione` = 'Il Monopattino elettrico Ibsun L10 ha un potente motore da 350W che può raggiungere fino ai 25km/h con un’autonomia di 58km e può trasportare un carico massimo di 150kg. È dotato di un sistema frenante meccanico ed elettrico Anti-Lock, che garantisce la sicurezza di frenata. Gli ammortizzatori anteriori e posteriori e gli ammortizzatori a molla anteriori garantiscono il massimo comfort e una guida fluida anche su superfici ruvide o dossi.' WHERE `veicoli`.`id_veicolo` = 81;
UPDATE `veicoli` SET `descrizione` = 'Il Monopattino elettrico Ibsun L10 ha un potente motore da 350W che può raggiungere fino ai 25km/h con un’autonomia di 58km e può trasportare un carico massimo di 150kg. È dotato di un sistema frenante meccanico ed elettrico Anti-Lock, che garantisce la sicurezza di frenata. Gli ammortizzatori anteriori e posteriori e gli ammortizzatori a molla anteriori garantiscono il massimo comfort e una guida fluida anche su superfici ruvide o dossi.' WHERE `veicoli`.`id_veicolo` = 82;
UPDATE `veicoli` SET `descrizione` = 'Il Monopattino elettrico Ibsun L10 ha un potente motore da 350W che può raggiungere fino ai 25km/h con un’autonomia di 58km e può trasportare un carico massimo di 150kg. È dotato di un sistema frenante meccanico ed elettrico Anti-Lock, che garantisce la sicurezza di frenata. Gli ammortizzatori anteriori e posteriori e gli ammortizzatori a molla anteriori garantiscono il massimo comfort e una guida fluida anche su superfici ruvide o dossi.' WHERE `veicoli`.`id_veicolo` = 83;

UPDATE `veicoli` SET `descrizione` = 'Il Monopattino elettrico Ibsun L10 ha un potente motore da 350W che può raggiungere fino ai 25km/h con un’autonomia di 58km e può trasportare un carico massimo di 150kg. È dotato di un sistema frenante meccanico ed elettrico Anti-Lock, che garantisce la sicurezza di frenata. Gli ammortizzatori anteriori e posteriori e gli ammortizzatori a molla anteriori garantiscono il massimo comfort e una guida fluida anche su superfici ruvide o dossi.' WHERE `veicoli`.`id_veicolo` = 84;
UPDATE `veicoli` SET `descrizione` = 'Il Monopattino elettrico Ibsun L10 ha un potente motore da 350W che può raggiungere fino ai 25km/h con un’autonomia di 58km e può trasportare un carico massimo di 150kg. È dotato di un sistema frenante meccanico ed elettrico Anti-Lock, che garantisce la sicurezza di frenata. Gli ammortizzatori anteriori e posteriori e gli ammortizzatori a molla anteriori garantiscono il massimo comfort e una guida fluida anche su superfici ruvide o dossi.' WHERE `veicoli`.`id_veicolo` = 85;
UPDATE `veicoli` SET `descrizione` = 'Il Monopattino elettrico Ibsun L10 ha un potente motore da 350W che può raggiungere fino ai 25km/h con un’autonomia di 58km e può trasportare un carico massimo di 150kg. È dotato di un sistema frenante meccanico ed elettrico Anti-Lock, che garantisce la sicurezza di frenata. Gli ammortizzatori anteriori e posteriori e gli ammortizzatori a molla anteriori garantiscono il massimo comfort e una guida fluida anche su superfici ruvide o dossi.' WHERE `veicoli`.`id_veicolo` = 86;
UPDATE `veicoli` SET `descrizione` = 'Il Monopattino elettrico Ibsun L10 ha un potente motore da 350W che può raggiungere fino ai 25km/h con un’autonomia di 58km e può trasportare un carico massimo di 150kg. È dotato di un sistema frenante meccanico ed elettrico Anti-Lock, che garantisce la sicurezza di frenata. Gli ammortizzatori anteriori e posteriori e gli ammortizzatori a molla anteriori garantiscono il massimo comfort e una guida fluida anche su superfici ruvide o dossi.' WHERE `veicoli`.`id_veicolo` = 87;