
UPDATE `veicoli` SET `tipologia`= 'Scooter,' WHERE `tipologia`= 'Motocicletta';

UPDATE `veicoli` SET `descrizione` = 'La nuova Vespa elettrica della Piaggio, Ha una velocità massima di 70km/h e rappresenta l’equilibrio perfetto tra innovazione ecologica e prestazioni di guida brillanti, ottimizzate grazie al perfezionamento di tutti i componenti tecnologici che la muovono. Usare Vespa Elettrica è semplice. Il vano sottosella, oltre ad accogliere il casco dedicato, contiene il cavo per la ricarica della batteria.
' WHERE `veicoli`.`id_veicolo` = 57;
UPDATE `veicoli` SET `descrizione` = 'La nuova Vespa elettrica della Piaggio, Ha una velocità massima di 70km/h e rappresenta l’equilibrio perfetto tra innovazione ecologica e prestazioni di guida brillanti, ottimizzate grazie al perfezionamento di tutti i componenti tecnologici che la muovono. Usare Vespa Elettrica è semplice. Il vano sottosella, oltre ad accogliere il casco dedicato, contiene il cavo per la ricarica della batteria.
' WHERE `veicoli`.`id_veicolo` = 58;
UPDATE `veicoli` SET `descrizione` = 'La nuova Vespa elettrica della Piaggio, Ha una velocità massima di 70km/h e rappresenta l’equilibrio perfetto tra innovazione ecologica e prestazioni di guida brillanti, ottimizzate grazie al perfezionamento di tutti i componenti tecnologici che la muovono. Usare Vespa Elettrica è semplice. Il vano sottosella, oltre ad accogliere il casco dedicato, contiene il cavo per la ricarica della batteria.
' WHERE `veicoli`.`id_veicolo` = 59;
UPDATE `veicoli` SET `descrizione` = 'La nuova Vespa elettrica della Piaggio, Ha una velocità massima di 70km/h e rappresenta l’equilibrio perfetto tra innovazione ecologica e prestazioni di guida brillanti, ottimizzate grazie al perfezionamento di tutti i componenti tecnologici che la muovono. Usare Vespa Elettrica è semplice. Il vano sottosella, oltre ad accogliere il casco dedicato, contiene il cavo per la ricarica della batteria.
' WHERE `veicoli`.`id_veicolo` = 60;
UPDATE `veicoli` SET `descrizione` = 'La nuova Vespa elettrica della Piaggio, Ha una velocità massima di 70km/h e rappresenta l’equilibrio perfetto tra innovazione ecologica e prestazioni di guida brillanti, ottimizzate grazie al perfezionamento di tutti i componenti tecnologici che la muovono. Usare Vespa Elettrica è semplice. Il vano sottosella, oltre ad accogliere il casco dedicato, contiene il cavo per la ricarica della batteria.
' WHERE `veicoli`.`id_veicolo` = 61;
UPDATE `veicoli` SET `descrizione` = 'La nuova Vespa elettrica della Piaggio, Ha una velocità massima di 70km/h e rappresenta l’equilibrio perfetto tra innovazione ecologica e prestazioni di guida brillanti, ottimizzate grazie al perfezionamento di tutti i componenti tecnologici che la muovono. Usare Vespa Elettrica è semplice. Il vano sottosella, oltre ad accogliere il casco dedicato, contiene il cavo per la ricarica della batteria.
' WHERE `veicoli`.`id_veicolo` = 62;
UPDATE `veicoli` SET `descrizione` = 'La nuova Vespa elettrica della Piaggio, Ha una velocità massima di 70km/h e rappresenta l’equilibrio perfetto tra innovazione ecologica e prestazioni di guida brillanti, ottimizzate grazie al perfezionamento di tutti i componenti tecnologici che la muovono. Usare Vespa Elettrica è semplice. Il vano sottosella, oltre ad accogliere il casco dedicato, contiene il cavo per la ricarica della batteria.
' WHERE `veicoli`.`id_veicolo` = 63;
UPDATE `veicoli` SET `descrizione` = 'La nuova Vespa elettrica della Piaggio, Ha una velocità massima di 70km/h e rappresenta l’equilibrio perfetto tra innovazione ecologica e prestazioni di guida brillanti, ottimizzate grazie al perfezionamento di tutti i componenti tecnologici che la muovono. Usare Vespa Elettrica è semplice. Il vano sottosella, oltre ad accogliere il casco dedicato, contiene il cavo per la ricarica della batteria.
' WHERE `veicoli`.`id_veicolo` = 64;
UPDATE `veicoli` SET `descrizione` = 'La nuova Vespa elettrica della Piaggio, Ha una velocità massima di 70km/h e rappresenta l’equilibrio perfetto tra innovazione ecologica e prestazioni di guida brillanti, ottimizzate grazie al perfezionamento di tutti i componenti tecnologici che la muovono. Usare Vespa Elettrica è semplice. Il vano sottosella, oltre ad accogliere il casco dedicato, contiene il cavo per la ricarica della batteria.
' WHERE `veicoli`.`id_veicolo` = 65;
UPDATE `veicoli` SET `descrizione` = 'La nuova Vespa elettrica della Piaggio, Ha una velocità massima di 70km/h e rappresenta l’equilibrio perfetto tra innovazione ecologica e prestazioni di guida brillanti, ottimizzate grazie al perfezionamento di tutti i componenti tecnologici che la muovono. Usare Vespa Elettrica è semplice. Il vano sottosella, oltre ad accogliere il casco dedicato, contiene il cavo per la ricarica della batteria.
' WHERE `veicoli`.`id_veicolo` = 66;